### ISSUE TITLE
Property addresses are not unique

### ISSUE THREAD

**Issue by Ashuh** [AY2122S2-CS2103-W16-4/tp#46]
Currently, it is possible to have multiple sellers with properties having identical addresses, which does not make sense.

Perhaps there should be a check to ensure that any new `Property` being added is unique, similar to the existing check to ensure that every `Person` has a unique name.

**Comment by waffledood** [comment]
I think it'd be possible to utilize `String`'s `hashCode()` method to compare between different addresses, but we'd have to account for leading, trailing whitespaces, mixture of cases (uppercase & lowercase).

```java
address.trim().toLowerCase.hashCode()
```

 I realize since the validation regex in Address is just `"[^\\s].*"`, it is possible for a user to input multiple whitespaces within the address, for example, <pre> `Pasir Ris Drive 1    Block 123 #01-01` </pre>

This could make comparing similar addresses more tricky. As it is, regexes for addresses are tricky because of the different address formats that exist. We could start by _not_ allowing certain symbols as done in this [StackOverflow post](https://stackoverflow.com/a/18853886/15781733). 

As for the above example containing multiple whitespaces, I'm not sure how we can approach that to prevent users/testers inputting similar addresses but in different formats, we might have to define a structure for addresses?
